### ISSUE TITLE
Give feedback on `TOP SECRET` page

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/Hotel-Zeitaku#1]
Submit this <a href="https://hotelzeitaku.netlify.app/#contact" target="_blank">form</a> on the website for a top secret page and tell me what you think and you can add your profile to my `README` as a feedback contributor 😄 
* You can can add your feedback as a comment below.  
* `Have you given your feedback?` great! now copy the first contributors template and edit with your details. 
_Let me know if you need any help_ 
<a href="https://hotelzeitaku.netlify.app/#contact"><img src="https://user-images.githubusercontent.com/62628408/117613274-8c128c00-b15e-11eb-9357-0715e4a6f461.png"></a>

**Comment by DenverCoder1** [comment]
Hi, great site! I assume you are referring to [this page](https://hotelzeitaku.netlify.app/thankyou). Here is my feedback.

* The image seems to be a bit low resolution and appears pixelated when stretched across the full background. Maybe consider finding a higher resolution version or an SVG if possible.
* The light blue background behind "Thank You" is a bit distracting. I would remove it for a more modern feel.
* While the octopus is behind the white text it makes it hard to read, I would try to avoid having the octopus pause while behind text. I would recommend moving the octopus gif higher up and the text lower so that the octopus pauses while above the text and not behind it. If you leave a gap at the bottom it can be filled with a background color.

<details>
<summary>Here's a gif showing my recommendations (click to show)</summary>

![zeitaku-loop](https://user-images.githubusercontent.com/20955511/117638048-1ffa4d00-b18b-11eb-8798-a99c688a2bcb.gif)

</details>

**Comment by Evavic44** [comment]
Oh hey @DenverCoder1, thank you so much for your feedback. 😎 🤩  
- I agree with what you said about the resolution of the gif, that was the best quality I could get from Dribbble. If you know any good place to get a higher quality image, do let me know. Thanks. 👍🏾 
- About the blue background text, yeah that's a good suggestion to -make the octopus wave above it. But I don't think I'll be removing the blue background from the text. I believe it's the highlight of the page and it matches with the color and all, but thanks for suggesting. Highly appreciate. 💯

**Comment by adarsh500** [comment]
I am viewing this on my laptop. The Zeitaku logo isn't centered.
Other than that, I love your color palette. 🌈
![Screen Shot 2021-05-10 at 3 55 43 PM](https://user-images.githubusercontent.com/73278151/117645541-56929080-b1a8-11eb-993f-d2324d9340b7.png)

**Comment by Evavic44** [comment]
> I am viewing this on my laptop. The Zeitaku logo isn't centered.
> Other than that, I love your color palette. 🌈
> ![Screen Shot 2021-05-10 at 3 55 43 PM](https://user-images.githubusercontent.com/73278151/117645541-56929080-b1a8-11eb-993f-d2324d9340b7.png)

Thanks for the review man, that logo has been the toughest div to center on the website, 😄 probably have to alter the flex property or something. If you have any ideas, maybe you can create a PR to fix it. If not, I'll raise an issue and work on it in my free time. 👍🏾

**Comment by Radon333** [comment]
1.There is a typos error. It should be **you're** instead of **youz're**
![issue](https://user-images.githubusercontent.com/25654606/118358941-aacdb400-b59e-11eb-8dfe-7e256ce08d14.png)

2.It would be great if you could centre the logo in navbar.

3.The logo in the bottom beside the copyright text is anchored to the same page(thankyou.html) itself which is unnecessary

**Comment by Evavic44** [comment]
> 1.There is a typos error. It should be **you're** instead of **youz're**
> ![issue](https://user-images.githubusercontent.com/25654606/118358941-aacdb400-b59e-11eb-8dfe-7e256ce08d14.png)
> 
> 2.It would be great if you could centre the logo in navbar.
> 
> 3.The logo in the bottom beside the copyright text is anchored to the same page(thankyou.html) itself which is unnecessary

Yeah, I've been so busy that I can't fix the typo. If you want, you can make a PR.   
I've created an issue for this: #5

**Comment by Ayushparikh-code** [comment]
nice layout but u can try make it more interactive using javascript !

**Comment by Evavic44** [comment]
> nice layout but u can try make it more interactive using javascript !

Do you have any suggestions? Do share with me. Thanks for the Feedback. 😇
